// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwGuT6CzFrcB8RzQ8hJsGdhvqNiKP3cmA',
    appId: '1:964181227971:web:48d6fef56fa0f3b17ee576',
    messagingSenderId: '964181227971',
    projectId: 'instagram-clone-israel',
    authDomain: 'instagram-clone-israel.firebaseapp.com',
    storageBucket: 'instagram-clone-israel.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEm5h-UT4rMAksefArnJfO3XHdME3BP3o',
    appId: '1:964181227971:android:19f50b54834355327ee576',
    messagingSenderId: '964181227971',
    projectId: 'instagram-clone-israel',
    storageBucket: 'instagram-clone-israel.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBakSIE-meKeRT9BMlQnSPwqD1rufOgCxI',
    appId: '1:964181227971:ios:47184997ea7238947ee576',
    messagingSenderId: '964181227971',
    projectId: 'instagram-clone-israel',
    storageBucket: 'instagram-clone-israel.appspot.com',
    iosClientId: '964181227971-5mgp6m3fko070rqa2122c9mnr6b2gc8b.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.instagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBakSIE-meKeRT9BMlQnSPwqD1rufOgCxI',
    appId: '1:964181227971:ios:47184997ea7238947ee576',
    messagingSenderId: '964181227971',
    projectId: 'instagram-clone-israel',
    storageBucket: 'instagram-clone-israel.appspot.com',
    iosClientId: '964181227971-5mgp6m3fko070rqa2122c9mnr6b2gc8b.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.instagramClone',
  );
}
